services:
  owncloud:
    image: owncloud/server:latest
    restart: always
    ports:
      - 3001:8080
    environment:
      - OWNCLOUD_DOMAIN=136.111.0.30
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=secret
      - OWNCLOUD_DB_HOST=db
    depends_on:
      - db
    volumes:
      - owncloud_files:/mnt/data

  db:
    image: mariadb:10.6
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=owncloud
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=secret
    volumes:
      - db_data:/var/lib/mysql

volumes:
  owncloud_files:
  db_data:
